# name: Deploy via SSH - Git pull, npm run build and deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: SSH into server and deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.REMOTE_USER }}
#           password: ${{ secrets.REMOTE_PASSWORD }}
#           port: 22
#           script: |
#             echo "Connecting to $REMOTE_HOST as $REMOTE_USER"
#             cd bims-mpit-final-backend
#             git pull origin master


